#!/bin/bash
if [ $# == 0 ]; then
  echo "Invalid: missing argument"
  exit 1
fi
INTERVAL=1
while [ true ]; do
  $@
  if [ $? == 0 ]; then
    INTERVAL=1
  else
    INTERVAL=$(($INTERVAL*2))
  fi
  sleep "$INTERVAL"
done
